# Generated by Django 6.0.5 on 2026-05-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('duenio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('informacion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('qr', models.ImageField(blank=True, upload_to='qr/')),
            ],
        ),
    ]
