# Generated by Django 6.0.5 on 2026-05-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='qr',
        ),
    ]
